name: ChangingParadigms
favicon: null
layout_spectrum: 0.6965836314484477
typography_spectrum: 0.6346256623510271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4782503095921129
  lightness: 0.0741301670204848
  saturation: 0.6596293428447098
  rhythmicContrast: 0.29698565090075135
purpose: []
