name: ChangingParadigms
favicon: null
layout_spectrum: 0.31403
typography_spectrum: 0.61114
title: Changing Paradigms - an AI blog site via The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040809'
    - '#797e81'
    - '#43555f'
    - '#c0b9a6'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
